name: "Unassign Inactive Contributors"

on:
  schedule:
    - cron: "*/1 * * * *" # Every minute
  workflow_call:

jobs:
  unassign-inactive:
    uses: SukhvirKooner/.github/.github/workflows/main.yaml
    with:
      inactivityPeriodInMinutes: 10
    secrets:
      github_Token: ${{ secrets.NEW_TOKEN }}
      

