name: "Unassign Inactive Contributors"

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minute
  workflow_call:

jobs:
  unassign-inactive:
    uses: SukhvirKooner/.github/.github/workflows/main.yaml@main
    with:
      inactivityPeriodInMinutes: 10
    secrets:
      github_Token: ${{ secrets.NEW_TOKEN }}