name: "Unassign Inactive Contributors"

on:
  schedule:
    - cron: "*/1 * * * *" # Every minute
  workflow_call:

jobs:
  unassign-inactive:
    uses: SukhvirKooner/.github/.github/workflows/main.yaml@main
    with:
      github_Token: ${{ secrets.WEB_TOKEN }}
      inactivityPeriodInMinutes: 10
      
